run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*_test.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused constants, variables, functions and types

    # Additional recommended linters
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues
    - gosec         # Inspects source code for security problems
    - misspell      # Finds commonly misspelled English words
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - gocyclo       # Computes and checks the cyclomatic complexity of functions
    - dupl          # Tool for code clone detection
    - bodyclose     # Checks whether HTTP response body is closed successfully
    - sqlclosecheck # Checks that sql.Rows and sql.Stmt are closed
    - rowserrcheck  # Checks whether Err of rows is checked successfully

  disable:
    - exhaustive    # Can be too strict
    - funlen        # Can be too opinionated
    - gochecknoglobals # Sometimes globals are necessary
    - gocognit      # Similar to gocyclo
    - godox         # Allow TODO comments
    - lll           # Line length can be handled by formatters
    - nlreturn      # Can be too opinionous
    - wsl           # Whitespace linter can be too strict
    - testpackage   # Not always necessary to use _test package

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow blank assignments like _ =
    # Ignore defer Close() calls - they're usually safe to ignore
    ignore: fmt:.*,io/ioutil:^Read.*,io:^Copy.*
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.DB).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close
      - (*os.File).Close
      - (*github.com/gorilla/websocket.Conn).Close
      - (*github.com/xuri/excelize/v2.File).SetCellValue
      - (*github.com/xuri/excelize/v2.File).NewSheet
      - (*github.com/xuri/excelize/v2.File).DeleteSheet
      - (*github.com/xuri/excelize/v2.File).AddDataValidation
      - (*github.com/xuri/excelize/v2.File).SetCellStyle
      - (*github.com/xuri/excelize/v2.File).SetColWidth
      - (*github.com/xuri/excelize/v2.File).NewStyle
      - (*github.com/xuri/excelize/v2.File).Close
      - (*github.com/xuri/excelize/v2.DataValidation).SetDropList
      - (*github.com/golang-migrate/migrate/v4.Migrate).Close
      - (*github.com/jackc/pgx/v5/pgxpool.Pool).Close

  govet:
    enable-all: true
    disable:
      - shadow # Can be too strict

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Duplicates errcheck
    config:
      G111: # Potential directory traversal
        exclude_dirs:
          - test

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

  gocyclo:
    min-complexity: 40  # Increased to allow more complex functions temporarily

  dupl:
    threshold: 400  # Increased to allow more code duplication temporarily

  misspell:
    locale: US
    ignore-words:
      - cancelled

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gci:
    sections:
      - standard # Standard packages
      - default # Default packages
      - prefix(github.com/Humfurie/pulpulitiko) # Project packages
    skip-generated: true

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocritic

    # Exclude known issues in generated files
    - path: mock_.*\.go
      linters:
        - all

    # Allow fmt.Println in main.go and skip complexity checks in cmd
    - path: cmd/.*\.go
      linters:
        - forbidigo
        - gocyclo
        - errcheck
        - gocritic

    # Exclude revive package comment warnings and naming issues
    - linters:
        - revive
      text: "(should have (a package comment|comment or be unexported)|comment on exported|var-naming|stutters|exported const)"

    # Exclude unused parameter warnings (will be addressed in future refactor)
    - linters:
        - revive
      text: "unused-parameter"

    # Exclude gocritic range copy and param combine warnings
    - linters:
        - gocritic
      text: "(rangeValCopy|paramTypeCombine|hugeParam|sprintfQuotedString|sloppyReassign|appendCombine)"

    # Exclude govet fieldalignment warnings
    - linters:
        - govet
      text: "fieldalignment"

    # Exclude unparam unused context and always nil warnings
    - linters:
        - unparam
      text: "(is unused|is always nil)"

    # Exclude gocritic commented-out code warnings
    - linters:
        - gocritic
      text: "commentedOutCode"

    # Exclude errcheck for import service (async operations)
    - path: internal/services/import_service\.go
      linters:
        - errcheck

    # Exclude ineffassign for repository files (dynamic query building)
    - path: internal/repository/.*\.go
      linters:
        - ineffassign

    # Exclude errcheck for type assertions in notification repository
    - path: internal/repository/notification_repository\.go
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

# Note: severity section removed as it's not supported in golangci-lint v2.x in this format
